id: A702B0AEB
title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed by Tsarchen
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:07:03.520843
  last_modified_at: 2022-03-01 04:07:03.520851
