id: A702B0AEB
title: 'The Jewelled Rosary: An Aspiration Toward Longed-for Aims'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:07:03.523281
  last_modified_at: 2022-03-01 04:07:03.523284
